# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ruminations of a Programmer Nerd
email: michael.campbell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just some stuff I think about.  Opinions are my own and I am not representing my employer nor their opinion in any way.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://unixgeek.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mcampbell_p
github_username:  mcampbell
resume_url: https://unixgeek.com/resume.html
mastodon:
  - instance: mastodon.social
  - username: mcampbell

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - bin/
  - ideas.txt
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - misc-notes.txt
